# Generated by Django 4.2.6 on 2024-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.EmailField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pre_test', models.CharField(max_length=255, null=True)),
                ('post_test', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
