# Generated by Django 5.0.2 on 2024-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStudent',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pre_test', models.CharField(max_length=255, null=True)),
                ('post_test', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=700)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='registerModel',
        ),
    ]
