# Generated by Django 5.0.2 on 2024-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0002_reportstudent_delete_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstudent',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
