# Generated by Django 5.0.2 on 2024-02-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0003_alter_reportstudent_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstudent',
            name='username',
        ),
    ]
