# Generated by Django 5.0.2 on 2024-02-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0005_alter_reportstudent_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_test', models.IntegerField(null=True)),
                ('post_test', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.BinaryField(max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PnHyWeb.role')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportStudent',
        ),
        migrations.AddField(
            model_name='reportscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PnHyWeb.student'),
        ),
    ]
