# Generated by Django 5.0.2 on 2024-02-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0006_reportscore_role_student_delete_reportstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
