# Generated by Django 5.0.2 on 2024-03-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0009_rename_student_reportscore_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportscore',
            old_name='student_id',
            new_name='student',
        ),
    ]
