# Generated by Django 5.0.2 on 2024-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PnHyWeb', '0011_remove_reportscore_id_alter_reportscore_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportscore',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PnHyWeb.student'),
        ),
    ]
